import type { Snapshot } from './types'

/** Offline console fallback; mirrors the safe civil-continuity baseline projection. */
export const fixtureSnapshot: Snapshot = {
  scenario: {
    id: 'broken-signal-v1',
    name: 'CIVIL CONTINUITY',
    classification: 'FICTIONAL TRAINING SIMULATION',
    correlation_id: 'run_fixture',
    time_ms: 0,
    sequence: 1,
    speed: 1,
    fixture_version: '1.0.0',
    seed: 4107,
    event_chain_head: 'fixture-genesis',
    demo_phase: {
      id: 'baseline',
      index: 1,
      total: 7,
      title: 'Calm baseline',
      cue: 'Twelve fictional civil resilience nodes are online. Continuity is intact.',
      operator_hint: 'Advance the synthetic evidence feed to begin the exercise.',
      label: 'fictional-exercise-phase',
      notice: 'Guided simulation pacing only; phases do not authorize external action.',
    },
  },
  network: {
    coordinator: 'northstar',
    availability: 100,
    metrics: {
      connected_components: 1,
      components: [['atlas', 'aurora', 'basalt', 'echo', 'fjord', 'harbor', 'kestrel', 'lumen', 'mosaic', 'northstar', 'ridge', 'vantage']],
      active_links: 21,
      unavailable_links: [],
      coordinator_reachable_nodes: 12,
      alternate_routes: 7,
      routes: {
        atlas: ['atlas', 'echo', 'northstar'],
        aurora: ['aurora', 'northstar'],
        basalt: ['basalt', 'aurora', 'northstar'],
        echo: ['echo', 'northstar'],
        fjord: ['fjord', 'harbor', 'northstar'],
        harbor: ['harbor', 'northstar'],
        kestrel: ['kestrel', 'fjord', 'harbor', 'northstar'],
        lumen: ['lumen', 'atlas', 'echo', 'northstar'],
        mosaic: ['mosaic', 'aurora', 'northstar'],
        northstar: ['northstar'],
        ridge: ['ridge', 'northstar'],
        vantage: ['vantage', 'echo', 'northstar'],
      },
      calculation_ms: 0,
    },
    nodes: [
      { id: 'northstar', callsign: 'NORTHSTAR', role: 'Coordination relay', x: 47, y: 34, latitude: 49, longitude: 31, status: 'online', is_coordinator: true, latency_ms: 18, links: ['ridge', 'echo', 'harbor', 'aurora'] },
      { id: 'ridge', callsign: 'RIDGE-7', role: 'Wide-area environmental sensor', x: 24, y: 22, latitude: 50.7, longitude: 26.2, status: 'online', is_coordinator: false, latency_ms: 31, links: ['northstar', 'echo', 'basalt'] },
      { id: 'echo', callsign: 'ECHO-3', role: 'Synthetic signal fusion', x: 33, y: 57, latitude: 49.8, longitude: 24.8, status: 'online', is_coordinator: false, latency_ms: 24, links: ['ridge', 'northstar', 'vantage', 'atlas', 'basalt'] },
      { id: 'harbor', callsign: 'HARBOR', role: 'Civil response liaison', x: 69, y: 24, latitude: 46.4, longitude: 30.4, status: 'online', is_coordinator: false, latency_ms: 42, links: ['northstar', 'vantage', 'fjord'] },
      { id: 'vantage', callsign: 'VANTAGE', role: 'Mobile environmental observation', x: 72, y: 61, latitude: 48.5, longitude: 35, status: 'online', is_coordinator: false, latency_ms: 37, links: ['echo', 'harbor', 'atlas', 'kestrel'] },
      { id: 'atlas', callsign: 'ATLAS-2', role: 'Recovery coordinator', x: 51, y: 75, latitude: 47.4, longitude: 31.5, status: 'online', is_coordinator: false, latency_ms: 29, links: ['vantage', 'echo', 'lumen'] },
      { id: 'aurora', callsign: 'AURORA-5', role: 'Atmospheric context station', x: 43, y: 15, latitude: 51.2, longitude: 28.5, status: 'online', is_coordinator: false, latency_ms: 34, links: ['northstar', 'basalt', 'mosaic'] },
      { id: 'basalt', callsign: 'BASALT', role: 'Edge compute cache', x: 30, y: 40, latitude: 49.1, longitude: 27.5, status: 'online', is_coordinator: false, latency_ms: 27, links: ['ridge', 'echo', 'aurora', 'lumen'] },
      { id: 'fjord', callsign: 'FJORD-4', role: 'Community message relay', x: 84, y: 34, latitude: 50.1, longitude: 36, status: 'online', is_coordinator: false, latency_ms: 49, links: ['harbor', 'kestrel', 'mosaic'] },
      { id: 'kestrel', callsign: 'KESTREL-6', role: 'Mobile emergency communications relay', x: 80, y: 72, latitude: 47.6, longitude: 35.5, status: 'online', is_coordinator: false, latency_ms: 33, links: ['vantage', 'fjord', 'lumen'] },
      { id: 'lumen', callsign: 'LUMEN', role: 'Power and health telemetry', x: 57, y: 88, latitude: 46.7, longitude: 33, status: 'online', is_coordinator: false, latency_ms: 26, links: ['atlas', 'basalt', 'kestrel', 'mosaic'] },
      { id: 'mosaic', callsign: 'MOSAIC-8', role: 'Archive and replay node', x: 65, y: 47, latitude: 49.4, longitude: 32.8, status: 'online', is_coordinator: false, latency_ms: 35, links: ['aurora', 'fjord', 'lumen'] },
    ],
  },
  prophet: {
    confidence: 36,
    state: 'nominal',
    warning_window_minutes: null,
    method: 'Deterministic scoring over labeled synthetic fixture',
    telemetry: {
      fixture_id: 'prophet-telemetry-v1',
      fixture_version: '1.0.0',
      sample_count: 17,
      pattern_onset_minute: -47,
      missing_data_samples: 1,
      false_positive_samples: 1,
      observed_events: 1,
      label_counts: { normal: 6, false_positive: 1, missing_data: 1, pattern_onset: 1, pre_event: 7, synthetic_event: 1 },
      source: 'deterministic-synthetic-generator',
      simulation_minute: -90,
      current_sample: {
        minute: -90,
        spectrum: 37,
        logistics: 43,
        network: 30,
        quality: 'complete',
        label: 'normal',
        event_observed: false,
      },
      playback_note: '90 fixture minutes compressed into 90 scenario seconds; nearest labeled row shown.',
    },
    evidence: {
      thresholds: { watch: 55, warning: 80 },
      confidence_interval: [22, 50],
      uncertainty_points: 14,
      confirming_signal_count: 1,
      top_contributors: [
        { id: 'spectrum', label: 'Civil radio congestion', contribution: 12 },
        { id: 'logistics', label: 'Utility service queue', contribution: 9 },
        { id: 'network', label: 'Emergency mesh traffic', contribution: 8 },
      ],
      state: 'nominal',
      data_quality: 'complete',
      missing_data_policy: 'Preserve null values and mark sample quality as partial; never impute silently.',
      false_positive_guardrail: 'Reviewed fixture case: a single-signal excursion remains below the multi-signal confirmation requirement and does not produce an alert.',
      calibration: {
        fixture_id: 'prophet-telemetry-v1',
        fixture_version: '1.0.0',
        method: 'Frozen linear calibration over weighted labeled synthetic evidence',
      },
    },
    countdown: {
      label: 'synthetic-virtual-time',
      pattern_onset_minute: -47,
      simulation_minute: -90,
      minutes_to_synthetic_event: 90,
      notice: 'Virtual-time fixture countdown only; not an operational launch clock.',
    },
    signals: [
      { id: 'spectrum', label: 'Civil radio congestion', value: 38, unit: '%', trend: 'stable', contribution: 12 },
      { id: 'logistics', label: 'Utility service queue', value: 44, unit: 'idx', trend: 'stable', contribution: 9 },
      { id: 'network', label: 'Emergency mesh traffic', value: 31, unit: 'idx', trend: 'stable', contribution: 8 },
    ],
  },
  mirror: {
    scenario_id: 'mirror-fictional-network-partition-v1',
    scenario_name: 'Eastern Europe civil communications continuity',
    classification: 'synthetic-training',
    seed: 4107,
    decision_point_id: 'relay-loss',
    condition: 'A fictional civil communications relay becomes unavailable during a generalized regional service disruption.',
    awaiting_choice: true,
    completed: false,
    branches: [
      { id: 'hold', label: 'Conservative hold', outcome: 'Maintain local review while diagnostics confirm simulated relay status.', assumption: 'Maintain local review while diagnostics confirm simulated relay status.' },
      { id: 'bridge', label: 'Civil bridge review', outcome: 'Evaluate a reversible simulated civil relay bridge with operator review.', assumption: 'Evaluate a reversible simulated civil relay bridge with operator review.' },
      { id: 'partition', label: 'Local partition', outcome: 'Keep fictional regions in local review mode pending further evidence.', assumption: 'Keep fictional regions in local review mode pending further evidence.' },
    ],
    selected_branch: null,
    trace_events: [],
    notice: 'Synthetic tabletop exercise informed by abstracted public reporting. All details are generated and generalized; no individual profiling, targeting, influence operations, or external action.',
  },
  citizen: {
    schema_version: 1,
    label: 'citizen-sensor-simulation',
    sensors_total: 5000,
    sensors_online: 5000,
    grid_survival_percent: 100,
    confirming_districts: 0,
    min_confirming_districts: 3,
    confidence: 0,
    state: 'listening',
    ready_for_warning: false,
    warning_dispatched: false,
    dispatch_channel: null,
    synthetic_lead_seconds: 240,
    advisory_districts: [],
    districts: [
      { id: 'd1', name: 'Riverside', sensors_online: 640, reporting: false },
      { id: 'd2', name: 'Old Market', sensors_online: 520, reporting: false },
      { id: 'd3', name: 'North Yards', sensors_online: 480, reporting: false },
      { id: 'd4', name: 'Foundry', sensors_online: 455, reporting: false },
      { id: 'd5', name: 'Garden Rows', sensors_online: 430, reporting: false },
      { id: 'd6', name: 'Rail Quarter', sensors_online: 410, reporting: false },
      { id: 'd7', name: 'Lakeside', sensors_online: 395, reporting: false },
      { id: 'd8', name: 'University', sensors_online: 380, reporting: false },
      { id: 'd9', name: 'Harbour Flats', sensors_online: 350, reporting: false },
      { id: 'd10', name: 'Hill Terrace', sensors_online: 335, reporting: false },
      { id: 'd11', name: 'West Gate', sensors_online: 315, reporting: false },
      { id: 'd12', name: 'Meadow End', sensors_online: 290, reporting: false },
    ],
    channels: [
      { id: 'sms', label: 'Cell broadcast / SMS', reach_percent: 96, status: 'available', active: true },
      { id: 'radio', label: 'Community FM relay', reach_percent: 71, status: 'available', active: false },
      { id: 'mesh', label: 'Offline mesh + siren relay', reach_percent: 48, status: 'available', active: false },
    ],
    privacy:
      'Anonymous district aggregates only; no device identity, precise location, or audio is retained.',
    notice:
      'Synthetic corroboration evidence for a human advisory decision. No trajectory estimation, no location of any source, and no targeting.',
    guardrail:
      'At least 3 independent districts and 55% corroboration are required before an operator may advise.',
  },
  phoenix: {
    workflow_status: 'degraded',
    approved_option: null,
    planner: {
      available_options: 4,
      ranking: ['availability', 'reliability', 'latency', 'reversibility'],
      notice: 'Non-lethal simulated workflow recovery only; human approval required.',
    },
    workflow: {
      workflow_id: 'wf_broken-signal-v1',
      correlation_id: 'run_fixture',
      state: 'alert',
      selected_option_id: null,
      approval_actor: null,
      transitions: [],
    },
    options: [
      { id: 'route-atlas', name: 'Promote ATLAS-2 relay', route: ['RIDGE-7', 'ECHO-3', 'ATLAS-2', 'VANTAGE'], availability: 100, reliability: 88, latency_seconds: 38, reversibility: 'high', rationale: 'Uses the recovery coordinator and existing signal-fusion relay.', status: 'recommended' },
      { id: 'route-harbor', name: 'Bridge through HARBOR', route: ['RIDGE-7', 'ECHO-3', 'VANTAGE', 'HARBOR'], availability: 100, reliability: 81, latency_seconds: 52, reversibility: 'high', rationale: 'Preserves the civil-response message relay with a slower bridge.', status: 'available' },
      { id: 'route-basalt', name: 'Activate BASALT cache relay', route: ['RIDGE-7', 'BASALT', 'LUMEN', 'ATLAS-2'], availability: 100, reliability: 79, latency_seconds: 44, reversibility: 'high', rationale: 'Uses cached synthetic telemetry when the primary coordination path is unavailable.', status: 'available' },
      { id: 'route-local', name: 'Operate local partitions', route: ['RIDGE-7', 'ECHO-3'], availability: 100, reliability: 76, latency_seconds: 14, reversibility: 'medium', rationale: 'Maintains local review workflows while full mesh recovery is unavailable.', status: 'available' },
    ],
    approval_policy: { operator: 1 },
    pre_approved: {
      schema_version: 1,
      label: 'simulation-preapproved-templates-v1',
      notice: 'Catalog only. Matching a template never auto-approves or executes recovery; an authenticated operator must still confirm.',
      auto_execute: false,
      templates: [],
    },
  },
  events: [
    {
      event_id: 'evt_fixture',
      correlation_id: 'run_fixture',
      sequence: 1,
      scenario_time_ms: 0,
      wall_time: new Date().toISOString(),
      source: 'scenario-engine',
      type: 'scenario.reset',
      severity: 'info',
      payload: { fixture: 'broken-signal-v1' },
      event_hash: 'fixture-genesis',
    },
  ],
}
